# -*- coding: utf-8 -*-
"""board.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uL7_Z3rvwtaoc-Tm488_gpr5Sgwa2iJj
"""

board = [
         ["-", "-", "-"],
         ["-", "-", "-"],
         ["-", "-", "-"]
]

def print_board():
  for row in board:
    print(row)