# -*- coding: utf-8 -*-
"""tictactoe.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GKMXQtjcYSvbJswP2HAbXoYnCWtxTxsJ
"""

import random

board = [
         ["-", "-", "-"],
         ["-", "-", "-"],
         ["-", "-", "-"]
]


def print_board():
  for row in board:
    print(row)

def check_mark(row, col):
  if board[row][col] == '-':
    return 'True'
  else:
    return 'False'


def place_mark(row, col, player_id):
  if player_id == 1:
    if check_mark(row, col) == 'True':
      board[row][col] = 'X'
    else:
      print('Space taken, please choose another space.')
  if player_id == 2:
    if check_mark(row, col) == 'True':
      board[row][col] = 'O'
    else:
      print('Space taken, please choose another space.')
    

def check_win(player_id):
  win = 'neither'
  if player_id == 1:
    for i in range(3):
      if board[i][0] == board[i][1] == board[i][2] and board[i][0] == 'X':
        win = 'player1'
      if board[0][i] == board[1][i] == board[2][i] and board[0][i] == 'X':
        win = 'player1'
    if board[1][1] == 'X':
      if board[0][0] == board[1][1] == board [2][2] or board [0][2] == board[1][1] == board[2][0]:
        win = 'player1'

    if win == 'player1':
      print('Player 1 wins!')
      return True
  
  if player_id == 2:
    for i in range(3):
      if board[i][0] == board[i][1] == board[i][2] and board[i][0] == 'O':
        win = 'player2'
      if board[0][i] == board[1][i] == board[2][i] and board[0][i] == 'O':
        win = 'player2'
    if board[1][1] == 'O':
      if board[0][0] == board[1][1] == board [2][2] or board [0][2] == board[1][1] == board[2][0]:
        win = 'player2'

    if win == 'player2':
      print('Player 2 wins!')
      return True
  return False

def check_draw(board):
  for row in board:
    for item in row:
      if item == '-':
        return False
  print("Draw!  No more spaces available!")
  return True


def intro():
  print('Tic Tac Toe Game')
  print()
  print('Player 1 is X and Player 2 is O.')
  print()


def firstMove():
  if random.randint(0, 1) == 0:
    return 'Player 1'
  else:
    return 'Player 2'


def game():
  startPlayer = firstMove()
  print(startPlayer, ' will go first!')
  x = 0
  o = 0
  if startPlayer == 'Player 1':
    o = 1
  else:
    x = 1

  while check_win(1) != True or check_win(2) != True or check_draw(board) != False:
    print()
    print_board()
    print()
    check_win(1)
    check_win(2)
    check_draw(board)

    if x < o:
      print("Player 1's turn")
      selection = int(input('Please enter a square number from 1-9: '))
      print()

      while selection >= 1 and selection <=9:
        if selection == 1:
          inputRow = 0
          inputCol = 0
          break
        elif selection == 2:
          inputRow = 0
          inputCol = 1
          break
        elif selection == 3:
          inputRow = 0
          inputCol = 2
          break
        elif selection == 4:
          inputRow = 1
          inputCol = 0
          break
        elif selection == 5:
          inputRow = 1
          inputCol = 1
          break
        elif selection == 6:
          inputRow = 1
          inputCol = 2
          break
        elif selection == 7:
          inputRow = 2
          inputCol = 0
          break
        elif selection == 8:
          inputRow = 2
          inputCol = 1
          break
        elif selection == 9:
          inputRow = 2
          inputCol = 2
          break
        else:
          print('Invalid square.')
      
      place_mark(inputRow, inputCol, 1)
      if check_win(1) == True:
        print_board()
        break
      else:
        x = x + 2
    else:
      print("Player 2's turn")
      selection = int(input('Please enter a square number from 1-9: '))
      print()
      
      while selection >= 1 and selection <=9:
        if selection == 1:
          inputRow = 0
          inputCol = 0
          break
        elif selection == 2:
          inputRow = 0
          inputCol = 1
          break
        elif selection == 3:
          inputRow = 0
          inputCol = 2
          break
        elif selection == 4:
          inputRow = 1
          inputCol = 0
          break
        elif selection == 5:
          inputRow = 1
          inputCol = 1
          break
        elif selection == 6:
          inputRow = 1
          inputCol = 2
          break
        elif selection == 7:
          inputRow = 2
          inputCol = 0
          break
        elif selection == 8:
          inputRow = 2
          inputCol = 1
          break
        elif selection == 9:
          inputRow = 2
          inputCol = 2
          break
        else:
          print('Invalid square.')
      
      place_mark(inputRow, inputCol, 2)
      if check_win(2) == True:
        print_board()
        break
      else:
        o = o + 2

  
def finish():
  print("Thank you for playing!")


def main():
  intro()
  game()
  finish()




main()